name: Add new publication

on:
  workflow_dispatch:
    inputs:
      doi:
        description: 'DOI of the paper'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-file:
    name: Add publication ${{ github.event.inputs.doi }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Add Publication
        run: uv run scripts/doi2yaml.py -i ${{ github.event.inputs.doi }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: add paper ${{ github.event.inputs.doi }}
          branch: doi/${{ github.event.inputs.doi }}
          title: add paper ${{ github.event.inputs.doi }}
          body: >
            You can use GitHub workflows to create or update pull requests adding new papers.
            Go to [Add new publication workflow page](https://github.com/TheChenGroup/TheChenGroup.github.io/actions/workflows/new-paper.yml),
            click on "Run workflow", and enter the DOI (e.g. `${{ github.event.inputs.doi }}`).
            A new pull request will automatically be created.
